### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by xiaoyaoshisishao** [lewei50/LeweiTcpClient#1]
Arduino: 1.5.4 (Mac OS X), Board: "Arduino Uno"

/Applications/Arduino_1.5.4.app/Contents/Resources/Java/libraries/LeweiTcpClient/LeweiTcpClient.cpp: In member function 'void LeweiTcpClient::readRom()':
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/libraries/LeweiTcpClient/LeweiTcpClient.cpp:215: error: ambiguous overload for 'operator=' in 'tmp = 0'
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:86: note: candidates are: String& String::operator=(const String&)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:87: note:                 String& String::operator=(const char_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:88: note:                 String& String::operator=(const __FlashStringHelper_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/libraries/LeweiTcpClient/LeweiTcpClient.cpp: In member function 'void LeweiTcpClient::listenServer()':
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/libraries/LeweiTcpClient/LeweiTcpClient.cpp:260: error: ambiguous overload for 'operator=' in 'clientStr = 0'
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:86: note: candidates are: String& String::operator=(const String&)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:87: note:                 String& String::operator=(const char_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:88: note:                 String& String::operator=(const __FlashStringHelper_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/libraries/LeweiTcpClient/LeweiTcpClient.cpp: In member function 'void LeweiTcpClient::getResponse()':
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/libraries/LeweiTcpClient/LeweiTcpClient.cpp:344: error: ambiguous overload for 'operator=' in '((LeweiTcpClient_)this)->LeweiTcpClient::_clientStr = 0'
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:86: note: candidates are: String& String::operator=(const String&)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:87: note:                 String& String::operator=(const char_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:88: note:                 String& String::operator=(const __FlashStringHelper_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/libraries/LeweiTcpClient/LeweiTcpClient.cpp:408: error: ambiguous overload for 'operator=' in 'functionName = 0'
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:86: note: candidates are: String& String::operator=(const String&)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:87: note:                 String& String::operator=(const char_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:88: note:                 String& String::operator=(const __FlashStringHelper_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/libraries/LeweiTcpClient/LeweiTcpClient.cpp:429: error: ambiguous overload for 'operator=' in '((LeweiTcpClient_)this)->LeweiTcpClient::_clientStr = 0'
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:86: note: candidates are: String& String::operator=(const String&)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:87: note:                 String& String::operator=(const char_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:88: note:                 String& String::operator=(const __FlashStringHelper_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/libraries/LeweiTcpClient/LeweiTcpClient.cpp: In member function 'String LeweiTcpClient::getParaValueStr(String&, String)':
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/libraries/LeweiTcpClient/LeweiTcpClient.cpp:450: error: conversion from 'int' to 'String' is ambiguous
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:61: note: candidates are: String::String(const __FlashStringHelper_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:59: note:                 String::String(const char_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/libraries/LeweiTcpClient/LeweiTcpClient.cpp: In member function 'void LeweiTcpClient::sendSensorValue(String, String)':
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/libraries/LeweiTcpClient/LeweiTcpClient.cpp:557: error: ambiguous overload for 'operator=' in 'connStr = 0'
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:86: note: candidates are: String& String::operator=(const String&)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:87: note:                 String& String::operator=(const char_)
/Applications/Arduino_1.5.4.app/Contents/Resources/Java/hardware/arduino/avr/cores/arduino/WString.h:88: note:                 String& String::operator=(const __FlashStringHelper_)

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by yangbo1979** [comment]
using arduino IDE version 1.0.5 to try it again.
